spring:
    datasource:
        url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
        username: ${PROD_DB_USERNAME}
        password: ${PROD_DB_PASSWORD}
        name: shop
    sql:
        init:
            mode: update
    jpa:
        generate-ddl: true
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                ddl-auto: create
                format_sql: true
                show-sql: true